// demo/react/src/pages/dashboard/_layout.tsx
import { NavLink, Outlet } from 'react-router-dom'

export default function DashboardLayout() {
  return (
    <div data-testid="dashboard-layout">
      <div className="demo-badges" style={{ marginBottom: '1rem' }}>
        <span className="demo-badge">嵌套 <strong>dashboard/_layout.tsx</strong></span>
        <span className="demo-badge">子路由在 children 内</span>
      </div>
      <nav className="demo-subnav" aria-label="Dashboard">
        <NavLink to="/dashboard" end>
          Overview
        </NavLink>
        <NavLink to="/dashboard/settings">Settings</NavLink>
      </nav>
      <div style={{ marginTop: '1rem' }}>
        <Outlet />
      </div>
    </div>
  )
}

// demo/vue/src/pages/dashboard/_layout.vue
<template>
  <div data-testid="dashboard-layout">
    <div class="demo-badges" style="margin-bottom: 1rem">
      <span class="demo-badge">嵌套 <strong>dashboard/_layout.vue</strong></span>
    </div>
    <nav class="demo-subnav" aria-label="Dashboard">
      <router-link to="/dashboard">Overview</router-link>
      <router-link to="/dashboard/settings">Settings</router-link>
    </nav>
    <div style="margin-top: 1rem">
      <router-view />
    </div>
  </div>
</template>
