// demo/vue/src/pages/index.vue
<script lang="ts">
export const meta = { title: 'Home' }
</script>

<script setup lang="ts">
import DemoPage from '../components/DemoPage.vue'
</script>

<template>
  <DemoPage
    title="Home"
    lead="index.vue 映射为根路径 /。meta 写入 routes.ts 的 meta 字段。"
    :badges="[
      { label: '文件', value: 'pages/index.vue' },
      { label: '加载', value: 'component: () => import(...)' },
    ]"
    code="pages/index.vue  +  export const meta = { title: 'Home' }"
  />
</template>

// demo/react/src/pages/index.tsx
import DemoPage from '../components/DemoPage'

export const meta = { title: 'Home' }

export default function Home() {
  return (
    <DemoPage
      title="Home"
      lead="根路由 index.tsx → URL /。演示默认懒加载与 export const meta 写入 routes 的 handle。"
      badges={[
        { label: '文件', value: 'pages/index.tsx' },
        { label: '加载', value: 'lazy (import)' },
        { label: 'meta', value: 'title → handle' },
      ]}
      code="pages/index.tsx  +  export const meta = { title: 'Home' }"
    />
  )
}
