// demo/react/src/pages/_layout.tsx
import { NavLink, Outlet } from 'react-router-dom'

import '../demo.css'

const NAV = [
  { to: '/', label: 'Home', tag: 'lazy' as const, hint: 'index + meta' },
  { to: '/about', label: 'About', tag: 'lazy' as const, hint: 'meta → handle' },
  { to: '/legal', label: 'Legal', tag: 'sync' as const, hint: '.sync.tsx' },
  { to: '/showcase', label: 'Showcase', tag: 'lazy' as const, hint: 'showcase.tsx' },
  { to: '/stats', label: 'Stats', tag: 'lazy' as const, hint: 'loader export' },
  { to: '/dashboard', label: 'Dashboard', tag: 'lazy' as const, hint: 'nested _layout' },
]

export default function RootLayout() {
  return (
    <div className="demo-app" data-testid="root-layout">
      <aside className="demo-sidebar">
        <div className="demo-brand">
          vite-plugin-file-router
          <span>React Router 7 demo</span>
        </div>
        <nav className="demo-nav" aria-label="Main">
          {NAV.map(({ to, label, tag }) => (
            <NavLink key={to} to={to} className={({ isActive }) => (isActive ? 'active' : undefined)}>
              <span>{label}</span>
              <span className={`demo-tag ${tag}`}>{tag}</span>
            </NavLink>
          ))}
          <NavLink to="/404-demo" className={({ isActive }) => (isActive ? 'active' : undefined)}>
            <span>404</span>
            <span className="demo-tag lazy">catch-all</span>
          </NavLink>
        </nav>
      </aside>
      <main className="demo-main">
        <Outlet />
      </main>
    </div>
  )
}

// demo/vue/src/pages/_layout.vue
<template>
  <div class="demo-app" data-testid="root-layout">
    <aside class="demo-sidebar">
      <div class="demo-brand">
        vite-plugin-file-router
        <span>Vue Router demo</span>
      </div>
      <nav class="demo-nav" aria-label="Main">
        <router-link to="/">Home</router-link>
        <router-link to="/about">About</router-link>
        <router-link to="/legal">
          <span>Legal</span>
          <span class="demo-tag sync">sync</span>
        </router-link>
        <router-link to="/showcase">Showcase</router-link>
        <router-link to="/dashboard">Dashboard</router-link>
        <router-link to="/user/42">Profile</router-link>
        <router-link to="/missing-page">
          <span>404</span>
          <span class="demo-tag lazy">catch-all</span>
        </router-link>
      </nav>
    </aside>
    <main class="demo-main">
      <router-view />
    </main>
  </div>
</template>
