// demo/react/src/pages/legal.sync.tsx
import DemoPage from '../components/DemoPage'

export default function LegalPage() {
  return (
    <DemoPage
      title="Legal"
      lead="legal.sync.tsx 使用 .sync 后缀，生成 routes.ts 顶部静态 import，打包进主 chunk。"
      badges={[
        { label: '文件', value: 'pages/legal.sync.tsx' },
        { label: '加载', value: 'sync' },
        { label: 'URL', value: '/legal' },
      ]}
      code="import LegalPage from './pages/legal.sync.tsx'  →  Component: LegalPage"
    />
  )
}

// demo/vue/src/pages/legal.sync.vue
<script setup lang="ts">
import DemoPage from '../components/DemoPage.vue'
</script>

<template>
  <DemoPage
    title="Legal"
    lead="legal.sync.vue 使用 .sync 后缀，routes.ts 顶部静态 import 后 component: LegalPage。"
    :badges="[
      { label: '文件', value: 'pages/legal.sync.vue' },
      { label: '加载', value: 'sync' },
    ]"
    code="import LegalPage from './pages/legal.sync.vue'"
  />
</template>
