// demo/react/src/pages/showcase.tsx
import DemoPage from '../components/DemoPage'

export default function ShowcasePage() {
  return (
    <DemoPage
      title="Showcase"
      lead="showcase.tsx → /showcase，标准懒加载页面。"
      badges={[
        { label: '源文件', value: 'pages/showcase.tsx' },
        { label: 'URL', value: '/showcase' },
        { label: '加载', value: 'lazy' },
      ]}
    >
      <p data-testid="showcase-note">路由路径：<strong>/showcase</strong></p>
    </DemoPage>
  )
}

// demo/vue/src/pages/showcase.vue
<route>
{
  "name": "showcase",
  "meta": { "title": "Showcase", "requiresAuth": true }
}
</route>

<script setup lang="ts">
import DemoPage from '../components/DemoPage.vue'
</script>

<template>
  <DemoPage
    title="Showcase"
    lead="&lt;route&gt; JSON 块在扫描时合并进 routes.ts；编译前需 Vite 插件剥离 SFC 中的 &lt;route&gt; 块。"
    :badges="[
      { label: '块', value: '&lt;route&gt; meta' },
      { label: 'requiresAuth', value: 'true' },
    ]"
    code='meta: { title: "Showcase", requiresAuth: true }'
  >
    <p data-testid="showcase-meta">Vue &lt;route&gt; block: requiresAuth = true</p>
  </DemoPage>
</template>
