// demo/react/src/components/DemoPage.tsx
import type { ReactNode } from 'react'

export type DemoBadge = { label: string; value: string }

export default function DemoPage({
  title,
  lead,
  badges,
  code,
  children,
}: {
  title: string
  lead: string
  badges?: DemoBadge[]
  code?: string
  children?: ReactNode
}) {
  return (
    <article className="demo-card">
      <h1>{title}</h1>
      <p className="demo-lead">{lead}</p>
      {badges && badges.length > 0 && (
        <div className="demo-badges">
          {badges.map((b) => (
            <span className="demo-badge" key={b.label}>
              {b.label}: <strong>{b.value}</strong>
            </span>
          ))}
        </div>
      )}
      {children}
      {code && <code className="demo-code">{code}</code>}
    </article>
  )
}

// demo/vue/src/components/DemoPage.vue
<script setup lang="ts">
defineProps<{
  title: string
  lead: string
  badges?: { label: string; value: string }[]
  code?: string
}>()
</script>

<template>
  <article class="demo-card">
    <h1>{{ title }}</h1>
    <p class="demo-lead">{{ lead }}</p>
    <div v-if="badges?.length" class="demo-badges">
      <span v-for="b in badges" :key="b.label" class="demo-badge">
        {{ b.label }}: <strong>{{ b.value }}</strong>
      </span>
    </div>
    <slot />
    <code v-if="code" class="demo-code">{{ code }}</code>
  </article>
</template>
